name: API
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.8
  - numpy=2.1.3
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - pytest=7.4.4
  - requests=2.32.3
  - fastapi=0.112.2
  - uvicorn=0.32.1
  - gunicorn=22.0.0
  - dvc=3.58.0
  - flake8=7.1.1
  - pip
  - pip:
      - dvc[s3]==3.2.0
